# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e42a75a57c8cf975ada6c968b98fcbafe6787dacfd0d4f13dae4f1841dc861735097df3c72d6f98d3aef6aa57549432d8d1bd02417a3fe0f1d30453262afcc1

test:
  secret_key_base: 8910c58dfdae36199c67b64cfd0198cbb968eed83cd892e6e445ab6e0e5406aad9ad3f96f3043d5b142115a284d44e92e063a7e84fa4212504b42bde03d8bc34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
